server:
  port: 8092
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/study?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 654321
  redis:
    database: 4
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 3000ms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 如果没有安装nacos服务，请设置为false
        enabled: true
      config:
        file-extension: yml
        server-addr: localhost:8848
        # 如果没有安装nacos服务，请设置为false
        enabled: false

swagger:
  production: true